### ISSUE TITLE
The future of the project.

### ISSUE THREAD

**Issue by commander-trashdin** [markcox80/specialization-store#3]
Hello sir.
Two questions:

1) Do you consider this library to be complete?
2) Do you care (=would you like to merge) if I add some extension (I can elaborate).

**Comment by markcox80** [comment]
I am quite happy with the project. Having said that, there are a few things in the project that need to be fixed and there are some parts which are broken.

I am of the view that more work needs to be done in the area of creating specializations (e.g. [template-function](https://github.com/markcox80/template-function)). This is where all of the hard work is.

What extension do you have in mind?

**Comment by commander-trashdin** [comment]
I had an idea about adding what could be considered (for the lack of the better word) typeclasses (as in Haskell).

The idea is simple -- there are some common operations, that some subsets of types share (such as all numbers share arithmetic operators, sequences can be concatenated, accessed, mapped over and so on, for some other types (such as custom ones) there can be others.) The idea is to make some sort of registry (which will be evaluated at compile time) and add there a tree of typeclasses, where each node contains all instances of a given typeclass. Instance should contain a table of type -> set of specific for the type function implementations. Since this whole thing would exist in compile-time, it would be possible to pass this typeclass instance instead of a type, and automatically replace all the functions/operators with more specific ones. I guess this can be easily macroed over you library.

**Comment by markcox80** [comment]
Assuming I have correctly understood what you have written above, I recommend either adding this functionality to [template-function](https://github.com/markcox80/template-function) or as a separate library.

The template function library already provides the ability to associate a template with an operator and request a specialization which is compiled from its template. From what I understand of your description, typeclasses are just an abstraction which maps a typeclass form to a set of operator specialization requests. This functionality doesn't exist in template-function and I would accept a patch for it.

FYI I have never used Haskell.

**Comment by commander-trashdin** [comment]
Okay, maybe you've heard about interfaces -- they serve similar purpose in a sense. 

I'll have a closer look at template function, I checked it once and saw last commit more then a year ago and kind of assumed that this was more like a refreshment lib. 
I'll get to it asap.

**Comment by commander-trashdin** [comment]
Sorry, that I only got my hands on it now, and not even fully.

Before I even try to get something real done, I wanna show you some sketch to know if you would consider it useful or ~

https://gist.github.com/thrashdin/2c02ec7bbe53fca532dc83c43614fb90

It kind of describes, how it should be working., For the record, I draw inspiration from https://www.haskell.org/tutorial/classes.html

**Comment by markcox80** [comment]
I have had a look at the sketch you have provided.

I am a bit confused by the type `(vector * (ord))` used in the [`deftemplate` example](https://gist.github.com/thrashdin/2c02ec7bbe53fca532dc83c43614fb90#file-lisp-L58). Is this referring to the CL type [`vector`](http://www.lispworks.com/documentation/HyperSpec/Body/t_vector.htm) or is it some other vector type?

**Comment by commander-trashdin** [comment]
Oh, that was supposed to mean a package specific type declaration -- this is the vector of _some type_ of objects,, we only know they belong to `ord` typeclass.

**Comment by commander-trashdin** [comment]
Here's (not mine) gist with a sketch, wdyt? That's a friend of mine, who's just way more experienced in lisp)

https://gist.github.com/Zulu-Inuoe/beb543b09b2fd6804f0772df85aac898

**Comment by markcox80** [comment]
The biggest issue I have with the first sketch is the [deftemplate line](https://gist.github.com/thrashdin/2c02ec7bbe53fca532dc83c43614fb90#file-lisp-L58) where the domain of the template is a vector of `ord` where `ord` is the typeclass defined [here](https://gist.github.com/thrashdin/2c02ec7bbe53fca532dc83c43614fb90#file-lisp-L38).

Consider the typeclass `ord2` which is defined in the same package as the `ord` typeclass provided in your sketch,
```lisp
(def-tc ord2 (eq)
  (<)
  (>)
  (min)
  (max))
```
and its associated template,
```lisp
(deftemplate foo-sort (seq :of-type (vector * (ord2)))
  ...)
```

What is supposed to happen in this instance? Is the operator `<` in the typeclass `ord` different to the operator in `ord2`?

Your previous post mentions the word interfaces. You didn't specify a definition but I assume you are referring to interfaces as defined in languages whereby a [single object](https://en.wikipedia.org/wiki/Dynamic_dispatch) is used to dispatch to a method implementation at runtime.

I have no interest in supporting single dispatch. I find the practice restrictive and confusing. State and operators which read and/or mutate said state should never be coupled syntactically. I have encountered situations where it becomes difficult to extend/fix other people's code. What is worse, it is common to end up with code which mixes function application (i.e. `my_function(object1, object2)`) and method invocation `(i.e. object1.myMethod(object2))`. Common lisp does not have either of these issues.

From what I can read from your description and sketch, a typeclass is nothing more than a collection of operators. If you restrict the operators to a set of template functions then I can see support for something like the following being added to the [template function library](https://github.com/markcox80/template-function).
```lisp
(define-template ord-< (a b)
  ...)

(define-template ord-> (a b)
  ...)

(define-template ord-min (a &rest args)
  ...)

(define-template ord-max (a &rest args)
  ...)

(define-template-set ord (<type>)
  (list `(ord-< ,<type> ,<type>)
        `(ord-> ,<type> ,<type>)
        `(ord-min ,<type> &rest ,<type>)
        `(ord-max ,<type> &rest ,<type>)))

(require-instantiations (ord double-float))
;;; (macroexpand '(require-instantiations (ord double-float)))
;;; =>
;;;  (require-instantiations (ord-< (double-float double-float))
;;;                          (ord-> (double-float double-float))
;;;                          (ord-min (double-float &rest double-float))
;;;                          (ord-max (double-float &rest double-float)))
```

I hope that helps.

Cheers.

P.S. My apologies for the delay. I hope you received my earlier email warning of you of the delay.

**Comment by commander-trashdin** [comment]
I haven't but no worries about that.

Stuff to say:
1)  I probably shouldn't use the word "interfaces", it's kind of confusing, so sorry for that.
2)  On similar names -- I gotta say I was thinking about, well, not allowing it basically -- doesn't make much sense to give similar names (instead of inheriting), if default typeclasses would be properly defined.
3) It actually is a collection of operators in a sense that -- well some types wanna have same operators and sometimes it is meaningful to group these types (and their opertors (and their implementations, if possible)) in the same place. So yeah, it doesn't add more functionality, just makes things a bit easier (from my point of view) to track, and probably a bit more coherent.

**Comment by markcox80** [comment]
I am going to close this discussion as I think it has been resolved.
