### ISSUE TITLE
Warnings while compiling specialization-store

### ISSUE THREAD

**Issue by mfiano** [markcox80/specialization-store#4]
```lisp
CL-USER> (ql:quickload :specialization-store)
To load "specialization-store":
  Load 1 ASDF system:
    specialization-store
; Loading "specialization-store"
WARNING:
   redefining SPECIALIZATION-STORE.LAMBDA-LISTS:PARAMETER-TYPE in DEFGENERIC
WARNING:
   redefining SPECIALIZATION-STORE.LAMBDA-LISTS:PARAMETER-KEYWORD in DEFGENERIC
```

**Comment by markcox80** [comment]
What implementation of common lisp are you using?

**Comment by mfiano** [comment]
SBCL 2.0.4 Linux/x86_64

**Comment by mfiano** [comment]
Just upgraded and same issue on SBCL 2.0.5

**Comment by mfiano** [comment]
In the package `SPECIALIZATION-STORE.LAMBDA-LISTS` you are defining the `defgeneric` forms, but then you are also defining them in the `SPECIALIZATION-STORE.DISPATCH` package which `:USE`s `SPECIALIZATION-STORE.LAMBDA-LISTS`.

**Comment by markcox80** [comment]
I cannot reproduce the output you posted at the start for some reason. I have the most recent quicklisp client and distribution plus sbcl-2.0.5 running with `--no-userinit`.

I have fixed the issue in branch [fix/issue4](https://github.com/markcox80/specialization-store/tree/fix/issue4). The unit tests pass. Please test against your code base and then I will make a new release.

**Comment by mfiano** [comment]
@markcox80 Xach and I were both able to reproduce it. It could be that you are not loading with verbosity enabled. Try `(setf ql:*quickload-verbose* t)`

**Comment by mfiano** [comment]
Yes, the fix is good and all my tests pass for a couple libraries that make heavy use of specialization-store. It looks good to release it.

**Comment by markcox80** [comment]
Thank you!

**Comment by markcox80** [comment]
I have submitted a [request](https://github.com/quicklisp/quicklisp-projects/issues/1859) to update the version of specialization-store in quicklisp.

**Comment by mfiano** [comment]
Thank you!
