### ISSUE TITLE
Why not MOP?

### ISSUE THREAD

**Issue by digikar99** [markcox80/specialization-store#5]
Hi! I found this project interesting, and would probably be useful for my own tasks. I shared it on [reddit](https://www.reddit.com/r/lisp/comments/iiqch9/markcox80specializationstore_a_imo_incredibly/), leading to a few questions. In particular your decision to not go with MOP. Like, does MOP happen to be insufficient for the tasks, or are there other reasons?

Thank you for the project!

**Comment by markcox80** [comment]
G'day Digikar99. Thank you for your interest in this project.

It has been many years since I started this project. I'll try and answer your question based on what I remember.

The primary objective of this work was to address the [motivating problem](https://github.com/markcox80/template-function/wiki/Motivating-the-Template-Function-System) for another project [template-function](https://github.com/markcox80/template-function).

To summarise the above link, the problem with implementing mathematical operators is that they are defined over a very large number of CL representations. That generality incurs a cost at runtime as every function invocation requires dispatching on the representation.

What I wanted was a function which had the performance advantages of inlining, but without sacrificing debugging/profiling (i.e. the function is no longer present on the call stack) or interactivity (i.e. needing to recompile everything when changing an inlined function). A consequence of this is that a lot of time is spent managing optimisations once knowledge of the representation is available (at compile time or at run time). 

I also wanted the ability to dispatch on optional and keyword arguments without resorting to an interface involving a function which invokes a generic function.

I also wanted the ability to dispatch according to the rank of an array and/or a subset of reals or integers. Dispatching on CL types (i.e. sets) creates issues which do not exist when using classes.

I felt (and still feel) that these requirements were sufficiently different from the goals of the MOP that it warranted a distinct interface.

**Comment by digikar99** [comment]
I definitely am feeling the need for templates in another project [numericals](https://github.com/digikar99/numericals). I was aware of [static-dispatch](https://github.com/alex-gutev/static-dispatch/) and [inlined-generic-function](https://github.com/guicho271828/inlined-generic-function) before, and [fast-generic-functions](https://github.com/marcoheisig/fast-generic-functions) more recently; but learnt that these do not support dispatching on types. 

>What I wanted was a function which had the performance advantages of inlining, but without sacrificing debugging/profiling

Could you elaborate this? Do you mean in the absence of `(my= :inline t)`? I do notice that not inlining trivial functions (like `string=`) can cause a huge performance penalty (10-100x more).

But I see your other points.

**Comment by markcox80** [comment]
I would have to see the code you are referring to for your performance analysis.

The profiler output for the function `foobar` in the code below will be mixed with the code for the function `my-very-long-function`.
```lisp
(declaim (inline my-very-long-function))
(defun my-very-long-function ()
  (sleep 10))

(defun foobar ()
  (print "Start")
  (my-very-long-function)
  (print "End"))
```

This is fine in this trivial example, but it can quickly become more complicated.

**Comment by digikar99** [comment]
My understanding of that statement was that the intention is to get as high a performance as possible, without inlining. However,

```lisp
(defstore my= (a b))
(defspecialization (my= :inline nil) ((a string) (b string)) boolean
  (string= a b))
(defun foo (a b)
  (declare (optimize speed)
           (type string a b))
  (loop for i below 10000000 do (my= a b)))
;;;;;;;;;;;;;;;;
SS-USER> (let ((a "hello")
               (b "world"))
           (time (foo a b)))
Evaluation took:
  0.632 seconds of real time
  0.631997 seconds of total run time (0.631997 user, 0.000000 system)
  100.00% CPU
  1,395,439,390 processor cycles
  0 bytes consed
```

while

```lisp
(defun bar (a b)
  (declare (optimize speed)
           (type string a b))
  (loop for i below 100000000 do (string= a b)))
;;;;;;;;;;;;;;;;
SS-USER> (let ((a "hello")
               (b "world"))
           (time (bar a b)))
Evaluation took:
  0.045 seconds of real time
  0.045841 seconds of total run time (0.045841 user, 0.000000 system)
  102.22% CPU
  101,210,536 processor cycles
  0 bytes consed

```

Or were you referring to something else?

**Comment by markcox80** [comment]
My apologies. I was referring to [named specializations](https://github.com/markcox80/specialization-store/wiki/Tutorial-3:-Compile-Time-Support#named-specializations).

**Comment by digikar99** [comment]
Hmm...

```lisp
(defmethod my-method ((a string) (b string))
  (let ((my-local-var (concatenate 'string a b)))
    (error "Hi ~A!" my-local-var)))
(defun foo (a b) (my-method a b))
```

Calling 

```lisp
CL-USER> (let ((a "hello")
               (b "world"))
           (foo a b))
``` 
results in
```lisp
Hi helloworld!
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {100AD91B63}>)

Backtrace:
  0: ((:METHOD MY-METHOD (STRING STRING)) "hello" "world") [fast-method]
      Locals:
        #:G8 = "hello"
        #:G9 = "world"
        MY-LOCAL-VAR = "helloworld"
  1: ((SB-PCL::GF-DISPATCH MY-METHOD) "hello" "world") ; This disappears if literal strings are put in the function call
  2: (FOO "hello" "world")
--more--
```

***

On the other hand

```lisp
(defstore my= (a b))
(defspecialization (my= :name my=/string) ((a string) (b string)) boolean
  (let ((my-local-var (concatenate 'string a b)))
    (error "Hi ~A!" my-local-var)))
(defun bar (a b) (my= a b))
```

Calling `(bar "hello" "world")` results in (same result if used a `let` form as above):

```lisp
Hi helloworld!
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {100AD91B63}>)

Backtrace:
  0: (MY=/STRING "hello" "world")
      Locals:
        #:G3 = "hello"
        #:G4 = "world"
        MY-LOCAL-VAR = "helloworld"
  1: ((LAMBDA (A B) :IN "/tmp/slimeyj9zuX") "hello" "world")
  2: ((LAMBDA (A B) :IN "/tmp/slimeGhnwJd.fasl") "hello" "world")
  3: (BAR "hello" "world")
  4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (BAR "hello" "world") #<NULL-LEXENV>)
  5: (EVAL (BAR "hello" "world"))
 --more--
```

But, I guess, never mind, the project looks good enough.

**Comment by markcox80** [comment]
I am confused. What are you expecting?

**Comment by digikar99** [comment]
I interpreted your reference to named specializations as intended towards better debugging purposes. 

***

When you started this project, inlined-generic-functions or the other projects, were in their initial stages, not even started or not as known. So, you starting this project is fully justified.

Owing to my lack of knowledge on MOP (either CLOS-MOP or the MOP for the current project), I'm in no position to judge which of the two ways - the way things are currently, or by using MOP - could be "better". If time permits some day, I might want to try something similar with MOP and generic functions; but at this point of time, this project fills a required niche (of dispatching on types - and keyword and optional args) and that's why this project is important.

**Comment by digikar99** [comment]
>What I wanted was a function which had the performance advantages of inlining, but without sacrificing debugging/profiling (i.e. the function is no longer present on the call stack) or interactivity (i.e. needing to recompile everything when changing an inlined function). A consequence of this is that a lot of time is spent managing optimisations once knowledge of the representation is available (at compile time or at run time).

And I think I get you now - after discovering this https://common-lisp.net/project/slime/doc/html/Profiling.html - and playing with it for some time. So, may be the following rephrase is more explanatory:

>I wanted a function that could be inlined when needed, but otherwise, was ammenable to profiling. The problem with generic functions are that they do not appear in the SLIME's profile trace. `specialization-store` solves this by providing the `:name` option that allows SLIME to profile the specific specialization.
