### ISSUE TITLE
Init-forms in specialization-lambda-list instead of store-lambda-list

### ISSUE THREAD

**Issue by digikar99** [markcox80/specialization-store#8]
I find this design choice a bit confusing:

```lisp
(defstore foo (a &key b))
(defspecialization foo ((a string) &key (b string)) t
  'hello)
```

Post the above code, is there some other way to allow the call `(foo "hello")` without redefining the `defstore` form? It seems okay for one-off systems, but a bit inconvenient for possibly extensible systems. Is specialization rather than extensibility the priority here?

EDIT: Found some relevant discussion in Design History, reading up on it.

**Comment by digikar99** [comment]
Okay, nope, I do not understand if https://github.com/markcox80/specialization-store/blob/master/doc/blog/20170508-init-forms.org addresses this issue. A partial way out seems to be 

```lisp
(defspecialization foo ((a string) &key (b null)) t
  'world)
```

but I don't see how to include a default argument for `b`; I'm inclined towards a syntax like:

```lisp
(defspecialization foo ((a string) &key ((b string) "default-string")) t
  'hello)
```

**Comment by markcox80** [comment]
The default value for the keyword argument is [obtained from the store function declaration](https://github.com/markcox80/specialization-store/wiki/Tutorial-2:-Optional,-Keyword-and-Rest-Arguments).

The reason for this is provided in the [wiki](https://github.com/markcox80/specialization-store/wiki):
> A premise of specialization store is that all specializations should perform the same task. Specializations should only differ in how the task is performed. This premise resolves ambiguities that arise when using types, rather than classes, to select the most specific specialization to apply.

**Comment by digikar99** [comment]
Hmm, okay, I need this point drilled home: specialization-store assumes that no matter what specialization is chosen, the final result will be the same. OTOH, for generic-functions, the case is that the final result is allowed to be different.

Okay, thanks for clarifying!

And this, apparantly, holds for `value-type` as well - the more specialized a specialization, the more specialized a value type can be specified.
